services:
  - type: web
    name: educase-school-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000

  - type: mysql
    name: educase-school-db
    plan: free
    ipAllowList: [] 